// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using WebApplication1.Data;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApplication1.Models.ColetaModel", b =>
                {
                    b.Property<int>("DiaColetaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DiaColetaId"));

                    b.Property<string>("Bairro")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("TipoColeta")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("DiaColetaId");

                    b.ToTable("TB_COLETA_MODEL", (string)null);
                });

            modelBuilder.Entity("WebApplication1.Models.DiaColeta", b =>
                {
                    b.Property<int>("DiaDeColetaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DiaDeColetaId"));

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("TIMESTAMP(7)");

                    b.HasKey("DiaDeColetaId");

                    b.ToTable("TB_DIA_COLETA", (string)null);
                });

            modelBuilder.Entity("WebApplication1.Models.Morador", b =>
                {
                    b.Property<int>("MoradorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MoradorId"));

                    b.Property<int>("Email")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("MoradorName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("MoradorId");

                    b.ToTable("TB_MORADOR", (string)null);
                });

            modelBuilder.Entity("WebApplication1.Models.Notificacao", b =>
                {
                    b.Property<int>("NotificacaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificacaoId"));

                    b.Property<int>("DiaColetaId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("MoradorId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("TipoResiduosId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("NotificacaoId");

                    b.HasIndex("DiaColetaId");

                    b.HasIndex("MoradorId");

                    b.HasIndex("TipoResiduosId");

                    b.ToTable("TB_NOTIFICACAO", (string)null);
                });

            modelBuilder.Entity("WebApplication1.Models.TipoResiduos", b =>
                {
                    b.Property<int>("TipoResiduosId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipoResiduosId"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("TipoResiduosId");

                    b.ToTable("TB_TIPO_RESIDUOS", (string)null);
                });

            modelBuilder.Entity("WebApplication1.Models.Notificacao", b =>
                {
                    b.HasOne("WebApplication1.Models.DiaColeta", "DiaColeta")
                        .WithMany()
                        .HasForeignKey("DiaColetaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplication1.Models.Morador", "Morador")
                        .WithMany()
                        .HasForeignKey("MoradorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplication1.Models.TipoResiduos", "TipoResiduos")
                        .WithMany()
                        .HasForeignKey("TipoResiduosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DiaColeta");

                    b.Navigation("Morador");

                    b.Navigation("TipoResiduos");
                });
#pragma warning restore 612, 618
        }
    }
}
